### PR TITLE
Fix issues with dobule quotes in task names

### PR DESCRIPTION
**Pull request by nvtkaszpir**
* double quotes in task names break searching elements in xpath
* convert clean_id to md5

TODO: tests ;)

### CODE REVIEW

**Comment by haidaraM** [comment]
Thanks for your PR. I will check that ASAP

**Comment by nvtkaszpir** [comment]
just create ansible task like this:
```
- name: Test task with "double quotes" in taskname
  command: /bin/true
```

**Comment by haidaraM** [comment]
just test it with `examples/example.yml`

example

Looks like `clean_name` needs some changes.

**Comment by nvtkaszpir** [comment]
Hm with my changes it shows:
example

python 2.7.9 with ansible 2.4.3.0

**Comment by haidaraM** [comment]
My bad. I tested in the wrong virtual env 😄

**Comment by haidaraM** [comment]
Realeased in `0.7.3`

**Pull request merged**
