### PR TITLE
fix: Fix include_role with loop

### LINKED ISSUE #80: include_role within a loop on role name to include generates an error
**Describe the bug**
When graphing a playbook with a task include_role within a loop on role name, ansible_playbook_grapher raise an execption :

**To Reproduce**
Assuming following playbook content snippet :
```yml
   - name: 'install docker and python addons'
      block:
        - include_role:
            name: '{{ item }}'
          loop:
            - certificates
            - docker
            - python_pip
            - python_docker
```

ansible_playbook_grapher raises an UndefinedError exception stating `item` is not defined

**Expected behavior**
ansible_playbook_grapher runs without exception

**Screenshots**
```text
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ansible/template/__init__.py", line 876, in do_template
    res = j2_concat(rf)
  File "<template>", line 11, in root
  File "/usr/lib/python3.6/site-packages/jinja2/runtime.py", line 635, in _fail_with_undefined_error
    raise self._undefined_exception(hint)
jinja2.exceptions.UndefinedError: 'item' is undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook-grapher", line 8, in <module>
    sys.exit(main())
  File "/home/..../.local/lib/python3.6/site-packages/ansibleplaybookgrapher/cli.py", line 188, in main
    cli.run()
  File "/home/..../.local/lib/python3.6/site-packages/ansibleplaybookgrapher/cli.py", line 175, in run
    grapher.make_graph()
  File "/home/..../.local/lib/python3.6/site-packages/ansibleplaybookgrapher/grapher.py", line 214, in make_graph
    play_vars=play_vars, node_name_prefix="[task] ")
  File "/home/..../.local/lib/python3.6/site-packages/ansibleplaybookgrapher/grapher.py", line 311, in _include_tasks_in_blocks
    variable_manager=self.variable_manager)
  File "/usr/lib/python3.6/site-packages/ansible/playbook/role_include.py", line 76, in get_block_list
    ri = RoleInclude.load(self._role_name, play=myplay, variable_manager=variable_manager, loader=loader, collection_list=self.collections)
  File "/usr/lib/python3.6/site-packages/ansible/playbook/role/include.py", line 60, in load
    return ri.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/usr/lib/python3.6/site-packages/ansible/playbook/base.py", line 222, in load_data
    ds = self.preprocess_data(ds)
  File "/usr/lib/python3.6/site-packages/ansible/playbook/role/definition.py", line 94, in preprocess_data
    (role_name, role_path) = self._load_role_path(role_name)
  File "/usr/lib/python3.6/site-packages/ansible/playbook/role/definition.py", line 152, in _load_role_path
    role_name = templar.template(role_name)
  File "/usr/lib/python3.6/site-packages/ansible/template/__init__.py", line 617, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python3.6/site-packages/ansible/template/__init__.py", line 910, in do_template
    raise AnsibleUndefinedVariable(e)
ansible.errors.AnsibleUndefinedVariable: 'item' is undefined
```

**Versions:**
 - ansible 2.9.14
  config file = /home/.../ansible.cfg
  configured module search path = ['/home/.../.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

 - ansible-playbook-grapher 0.10.0 (with ansible 2.9.14)

### PR DESCRIPTION
**Pull request by haidaraM**
Should fix #80

### CODE REVIEW

**Comment by fiskhest** [comment]
Hi @haidaraM 

My impression is that the changes would display a warning, but still continue running what it possibly can parse? 

I'm still seeing crashes after trying this code:

```
❯ ~/.pyenv/versions/3.9.1/envs/apg/bin/ansible-playbook-grapher  entry-plan.yml --include-role-tasks -i inventory/tf_inventory.py
[WARNING]: ansible.utils.display.initialize_locale has not been called, this may result in incorrectly calculated text widths that can cause Display to print incorrect line lengths

Parsing Play: generate plan order (1) **************************************************************************************************************************************************************
[WARNING]: Including role with loop is not supported for the moment. The include will not be evaluated.
Traceback (most recent call last):
  File "/home/johan/.pyenv/versions/3.9.1/envs/apg/bin/ansible-playbook-grapher", line 33, in <module>
    sys.exit(load_entry_point('ansible-playbook-grapher==1.0.1', 'console_scripts', 'ansible-playbook-grapher')())
  File "/home/johan/.pyenv/versions/apg/lib/python3.9/site-packages/ansible_playbook_grapher-1.0.1-py3.9.egg/ansibleplaybookgrapher/cli.py", line 126, in main
    cli.run()
  File "/home/johan/.pyenv/versions/apg/lib/python3.9/site-packages/ansible_playbook_grapher-1.0.1-py3.9.egg/ansibleplaybookgrapher/cli.py", line 43, in run
    playbook_node = parser.parse()
  File "/home/johan/.pyenv/versions/apg/lib/python3.9/site-packages/ansible_playbook_grapher-1.0.1-py3.9.egg/ansibleplaybookgrapher/parser.py", line 179, in parse
    self._include_tasks_in_blocks(current_play=play, parent_nodes=[role_node], block=block,
  File "/home/johan/.pyenv/versions/apg/lib/python3.9/site-packages/ansible_playbook_grapher-1.0.1-py3.9.egg/ansibleplaybookgrapher/parser.py", line 289, in _include_tasks_in_blocks
    self._include_tasks_in_blocks(current_play=current_play, parent_nodes=parent_nodes, block=b,
  File "/home/johan/.pyenv/versions/apg/lib/python3.9/site-packages/ansible_playbook_grapher-1.0.1-py3.9.egg/ansibleplaybookgrapher/parser.py", line 317, in _include_tasks_in_blocks
    parent_node=parent_nodes[-1])
IndexError: list index out of range
```

I can create a new issue if you'd prefer tracking this separately, just lmk.

**Comment by haidaraM** [comment]
Can you provide me a minimal version of your playbook that is failing or run with `-vvv` and send me the logs? 

No need to create a new issue. I will reopen the old one :-)

**Comment by haidaraM** [comment]
It displays a warning and moves on to the next task but in your case, I have missed something.

**Comment by fiskhest** [comment]
To create a minimal reproducible version of my playbook I reverse engineered to understand what task is failing, 

```
try:
    self._add_task(task=task_or_block, task_vars=play_vars, node_type=node_type,
                   parent_node=parent_nodes[-1])
except IndexError:
    breakpoint()

-> for task_or_block in block.block:
(Pdb) task_or_block
TASK: meta/plan : Include the dynamically generated resource plan
(Pdb)
```
```
- name: Include the dynamically generated resource plan
  ansible.builtin.include_vars:
    dir: "{{ tenant_dir }}/pipeline/virtual_machines/"
    name: resources
    hash_behaviour: merge
```

I tried to replicate the include-pasta I've created a simple role that tries to trigger the same issue but that runs as intended. The source is too complex and containing secrets that I do not wish to share. Will continue trying to replicate it minimally but I got no further ideas so leaving this here for now.

**Comment by fiskhest** [comment]
Certainly, one moment.

**Pull request merged**
