### PR TITLE
fix: Fix include_role with loop and list index out of range

### PR DESCRIPTION
**Pull request by haidaraM**
Related to #80

### CODE REVIEW

**Comment by fiskhest** [comment]
If that even was the actual issue. Anyhow, I now get a successful execution and no traceback. Thanks for the impressive turnaround!

**Comment by fiskhest** [comment]
Excuse my ignorance, and perhaps off topic, but curious to understand why it's not possible to parse if a loop was combined with the includes? What's been introduced so far is real nice and I'm grateful for that!

**Comment by haidaraM** [comment]
No worries :-) The main issue was with the loop and some changes I introduced in this PR https://github.com/haidaraM/ansible-playbook-grapher/pull/92. Include works if the target file can be loaded statically.


The grapher relies on Ansible's internals to **statically parse** the playbook and include the plays, tasks, and roles. Since Ansible evaluates some loops during the **execution of the playbook**, the grapher will need to **simulate** this behavior to get the loop results and then include the resulting tasks. I will see if I can support it without introducing too much complexity in the future.

**Comment by fiskhest** [comment]
Understood, I feared as much. (Already ran into that limitation when my first use case was appending --list-tasks to ansible-playbook). Thanks for clarifying.

**Pull request merged**
